CREATE TABLE vehicle (
	id INT generated by default as identity (start with 10),
	carClass VARCHAR(255) NOT NULL,	
	price  FLOAT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE booking (
	reservation_number VARCHAR(255) NOT NULL,
	vehicle_id INT NOT NULL,
	pickup_date TIMESTAMP NOT NULL,
	PRIMARY KEY (reservation_number),
	FOREIGN KEY (vehicle_id) REFERENCES vehicle(id)
);
	